export DOTFILES=$HOME/.dotfiles

# your project folder that we can `c [tab]` to
export PROJECTS=~/www

# source every .bash file
for file in $HOME/.dotfiles/**/*.bash; do
  [ -r "$file" ] && source "$file"
done
unset file

# use .localrc for settings specific to one system
# if [ -f ~/.localrc ]; then
#   source ~/.localrc
# fi